/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenii;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ESFOT
 */
public class Triangulofrm extends javax.swing.JFrame {
    
    
    DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
    FiguraAyP f; 
    /**
     * Creates new form Triangulofrm
     */
    public Triangulofrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbFigura = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        panelEscaleno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLado1Es = new javax.swing.JTextField();
        txtLado2Es = new javax.swing.JTextField();
        txtLado3Es = new javax.swing.JTextField();
        btnCalcularEs = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAreaEs = new javax.swing.JTextField();
        txtPerimetroEs = new javax.swing.JTextField();
        txtAlturaEs = new javax.swing.JTextField();
        panelEquilatero = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtladoEq = new javax.swing.JTextField();
        txtAreaEq = new javax.swing.JTextField();
        txtPerimetroEq = new javax.swing.JTextField();
        txtAlturaEq = new javax.swing.JTextField();
        btnCalularEquilatero = new javax.swing.JButton();
        panelIsosceles = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtLado1Is = new javax.swing.JTextField();
        txtLado2Is = new javax.swing.JTextField();
        txtAreaIs = new javax.swing.JTextField();
        txtPerimetroIs = new javax.swing.JTextField();
        txtAlturaIs = new javax.swing.JTextField();
        btnCalularIs = new javax.swing.JButton();
        panelRectangulo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtLado1Re = new javax.swing.JTextField();
        txtLado2Re = new javax.swing.JTextField();
        txtAreaRe = new javax.swing.JTextField();
        txtPerimetroRe = new javax.swing.JTextField();
        txtAlturaRe = new javax.swing.JTextField();
        btnCalcularRe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Triangulos");

        cmbFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escaleno", "Equilatero", "Isosceles", "Rectangulo" }));
        cmbFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiguraActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar Figura");

        jLabel2.setText("Lado1");

        jLabel3.setText("lado2");

        jLabel4.setText("lado3");

        btnCalcularEs.setText("Calcular");
        btnCalcularEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEsActionPerformed(evt);
            }
        });

        jLabel5.setText("Area");

        jLabel6.setText("Perimetro");

        jLabel7.setText("Altura");

        txtAreaEs.setEditable(false);

        txtPerimetroEs.setEditable(false);

        txtAlturaEs.setEditable(false);

        javax.swing.GroupLayout panelEscalenoLayout = new javax.swing.GroupLayout(panelEscaleno);
        panelEscaleno.setLayout(panelEscalenoLayout);
        panelEscalenoLayout.setHorizontalGroup(
            panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscalenoLayout.createSequentialGroup()
                .addComponent(btnCalcularEs)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelEscalenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEscalenoLayout.createSequentialGroup()
                        .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscalenoLayout.createSequentialGroup()
                                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(44, 44, 44))
                            .addGroup(panelEscalenoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)))
                        .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLado3Es, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(txtLado2Es)
                                .addComponent(txtLado1Es))
                            .addComponent(txtAreaEs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEscalenoLayout.createSequentialGroup()
                        .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimetroEs)
                            .addComponent(txtAlturaEs))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelEscalenoLayout.setVerticalGroup(
            panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscalenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLado1Es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtLado2Es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtLado3Es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtAreaEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPerimetroEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscalenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAlturaEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularEs)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel8.setText("Lado 1");

        jLabel9.setText("Area");

        jLabel10.setText("Perimetro");

        jLabel11.setText("Altura");

        txtAreaEq.setEditable(false);

        txtPerimetroEq.setEditable(false);

        txtAlturaEq.setEditable(false);

        btnCalularEquilatero.setText("Calcular");
        btnCalularEquilatero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalularEquilateroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEquilateroLayout = new javax.swing.GroupLayout(panelEquilatero);
        panelEquilatero.setLayout(panelEquilateroLayout);
        panelEquilateroLayout.setHorizontalGroup(
            panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquilateroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEquilateroLayout.createSequentialGroup()
                        .addGroup(panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(60, 60, 60)
                        .addGroup(panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimetroEq, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAreaEq, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlturaEq)
                            .addGroup(panelEquilateroLayout.createSequentialGroup()
                                .addComponent(txtladoEq, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 45, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(panelEquilateroLayout.createSequentialGroup()
                        .addComponent(btnCalularEquilatero)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelEquilateroLayout.setVerticalGroup(
            panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquilateroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtladoEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtAreaEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtPerimetroEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtAlturaEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalularEquilatero)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jLabel12.setText("Lado 1");

        jLabel13.setText("Lado 2");

        jLabel14.setText("Area");

        jLabel15.setText("Perimetro");

        jLabel16.setText("Altura");

        txtAreaIs.setEditable(false);

        txtPerimetroIs.setEditable(false);

        txtAlturaIs.setEditable(false);

        btnCalularIs.setText("Calcular");
        btnCalularIs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalularIsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIsoscelesLayout = new javax.swing.GroupLayout(panelIsosceles);
        panelIsosceles.setLayout(panelIsoscelesLayout);
        panelIsoscelesLayout.setHorizontalGroup(
            panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsoscelesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12))
                .addGap(25, 25, 25)
                .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIsoscelesLayout.createSequentialGroup()
                        .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLado2Is)
                            .addComponent(txtLado1Is))
                        .addGap(62, 62, 62))
                    .addGroup(panelIsoscelesLayout.createSequentialGroup()
                        .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPerimetroIs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAreaIs))
                        .addContainerGap())
                    .addGroup(panelIsoscelesLayout.createSequentialGroup()
                        .addComponent(txtAlturaIs)
                        .addContainerGap())))
            .addGroup(panelIsoscelesLayout.createSequentialGroup()
                .addComponent(btnCalularIs)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelIsoscelesLayout.setVerticalGroup(
            panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsoscelesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtLado1Is, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLado2Is, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaIs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPerimetroIs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIsoscelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtAlturaIs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalularIs)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLabel17.setText("Lado 1");

        jLabel18.setText("Lado 2");

        jLabel19.setText("Area");

        jLabel20.setText("Perimetro");

        jLabel21.setText("Altura");

        txtAreaRe.setEditable(false);

        txtPerimetroRe.setEditable(false);
        txtPerimetroRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetroReActionPerformed(evt);
            }
        });

        txtAlturaRe.setEditable(false);

        btnCalcularRe.setText("Calcular");
        btnCalcularRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularReActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRectanguloLayout = new javax.swing.GroupLayout(panelRectangulo);
        panelRectangulo.setLayout(panelRectanguloLayout);
        panelRectanguloLayout.setHorizontalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcularRe)
                    .addGroup(panelRectanguloLayout.createSequentialGroup()
                        .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(46, 46, 46)
                        .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLado1Re, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtLado2Re)
                            .addComponent(txtPerimetroRe)
                            .addComponent(txtAlturaRe)
                            .addComponent(txtAreaRe))))
                .addGap(27, 27, 27))
        );
        panelRectanguloLayout.setVerticalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtLado1Re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtLado2Re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtAreaRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPerimetroRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtAlturaRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularRe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelEscaleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(panelEquilatero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelIsosceles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEscaleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEquilatero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIsosceles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiguraActionPerformed
        // TODO add your handling code here:
        
        String figuraSlc = (String)cmbFigura.getSelectedItem();
        
        if(figuraSlc.equals("Escaleno")){
        panelEscaleno.setVisible(true);
        panelEquilatero.setVisible(false);
        panelIsosceles.setVisible(false);
        panelRectangulo.setVisible(false);
       
        
        }
        else if(figuraSlc.equals("Equilatero")){
        panelEscaleno.setVisible(false);
        panelEquilatero.setVisible(true);
        panelIsosceles.setVisible(false);
        panelRectangulo.setVisible(false);
        
        }
        else if(figuraSlc.equals("Isosceles")){
        panelEscaleno.setVisible(false);
        panelEquilatero.setVisible(false);
        panelIsosceles.setVisible(true);
        panelRectangulo.setVisible(false);
      
        
        }
        else if(figuraSlc.equals("Rectangulo")){
        panelEscaleno.setVisible(false);
        panelEquilatero.setVisible(false);
        panelIsosceles.setVisible(false);
        panelRectangulo.setVisible(true);
       
        
        }else{
        }
        
        
    }//GEN-LAST:event_cmbFiguraActionPerformed

    private void btnCalularEquilateroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalularEquilateroActionPerformed
        // TODO add your handling code here:
        double lado1=Double.parseDouble(txtladoEq.getText());
        double lado2=lado1; double lado3=lado1;
        
        if(lado1+lado2>lado3 && lado2+lado3>lado1 && lado3 + lado1>lado2){
            
            f=new Equilatero(lado1);
            double a =f.calcularArea();
            double b= f.calcularPerimetro();
            double h= f.calcularAltura();
            String areaEq= String.valueOf(a);
            String perimetroEq=String.valueOf(b);
            String aulturaEq=String.valueOf(h);
            txtAreaEq.setText(areaEq);
            txtPerimetroEq.setText(perimetroEq);
            txtAlturaEq.setText(aulturaEq);
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se puede formar un triangulo con esos daros");
            txtLado1Re.setText(" ");
            txtLado2Re.setText(" ");
            txtAreaRe.setText(" ");
            txtPerimetroRe.setText(" ");
            txtAlturaRe.setText(" ");
        }
       
        
    }//GEN-LAST:event_btnCalularEquilateroActionPerformed

    private void txtPerimetroReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetroReActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetroReActionPerformed

    private void btnCalcularEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEsActionPerformed
        // TODO add your handling code here:
        double lado1= Double.parseDouble(txtLado1Es.getText());
        double lado2= Double.parseDouble(txtLado2Es.getText());
        double lado3= Double.parseDouble(txtLado3Es.getText());
        
        
        if(lado1+lado2>lado3 && lado2+lado3>lado1 && lado3 + lado1>lado2){
        if(lado1==lado2|| lado2==lado3 || lado3==lado1){
            JOptionPane.showMessageDialog(rootPane, "Ingrese lados diferentes");
            txtLado1Es.setText(" ");
            txtLado2Es.setText(" ");
            txtLado3Es.setText(" ");
        }else{
            f = new Escaleno(lado1,lado2,lado3);
            double a =f.calcularArea();
            double b= f.calcularPerimetro();
            double h= f.calcularAltura();
            String areaEs= String.valueOf(a);
            String perimetroEs=String.valueOf(b);
            String aulturaEs=String.valueOf(h);
            txtAreaEs.setText(areaEs);
            txtPerimetroEs.setText(perimetroEs);
            txtAlturaEs.setText(aulturaEs);
        }
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se puede formar un triangulo con esos daros");
            txtLado1Es.setText(" ");
            txtLado2Es.setText(" ");
            txtLado3Es.setText(" ");
            txtAreaEs.setText(" ");
            txtPerimetroEs.setText(" ");
            txtAlturaEs.setText(" ");
        }
        
        
    }//GEN-LAST:event_btnCalcularEsActionPerformed

    private void btnCalularIsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalularIsActionPerformed
        // TODO add your handling code here:
        double lado1= Double.parseDouble(txtLado1Is.getText());
        double lado2= Double.parseDouble(txtLado2Is.getText());
        double lado3=lado1;
        
       
        
        if(lado1+lado2>lado3 && lado2+lado3>lado1 && lado3 + lado1>lado2){
            
             
            
            f= new Isosceles(lado1,lado2);
            double a =f.calcularArea();
            double b= f.calcularPerimetro();
            double h= f.calcularAltura();
            String areaIs= String.valueOf(a);
            String perimetroIs=String.valueOf(b);
            String aulturaIs=String.valueOf(h);
            txtAreaIs.setText(areaIs);
            txtPerimetroIs.setText(perimetroIs);
            txtAlturaIs.setText(aulturaIs);
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se puede formar un triangulo con esos daros");
            txtLado1Is.setText(" ");
            txtLado2Is.setText(" ");
            txtAreaIs.setText(" ");
            txtPerimetroIs.setText(" ");
            txtAlturaIs.setText(" ");
        }
        
        
    }//GEN-LAST:event_btnCalularIsActionPerformed

    private void btnCalcularReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularReActionPerformed
        // TODO add your handling code here:
        double lado1= Double.parseDouble(txtLado1Re.getText());
        double lado2= Double.parseDouble(txtLado2Re.getText());
        double lado3= (float)Math.sqrt((lado1)*(lado1)+(lado2)*(lado2));
        
        if(lado1+lado2>lado3 && lado2+lado3>lado1 && lado3 + lado1>lado2){
            f = new Rectangulo(lado1,lado2);
            double a =f.calcularArea();
            double b= f.calcularPerimetro();
            double h= f.calcularAltura();
            String areaRe= String.valueOf(a);
            String perimetroRe=String.valueOf(b);
            String aulturaRe=String.valueOf(h);
            txtAreaRe.setText(areaRe);
            txtPerimetroRe.setText(perimetroRe);
            txtAlturaRe.setText(aulturaRe);
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se puede formar un triangulo con esos daros");
            txtLado1Re.setText(" ");
            txtLado2Re.setText(" ");
            txtAreaRe.setText(" ");
            txtPerimetroRe.setText(" ");
            txtAlturaRe.setText(" ");
        }
        
    }//GEN-LAST:event_btnCalcularReActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulofrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularEs;
    private javax.swing.JButton btnCalcularRe;
    private javax.swing.JButton btnCalularEquilatero;
    private javax.swing.JButton btnCalularIs;
    private javax.swing.JComboBox<String> cmbFigura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelEquilatero;
    private javax.swing.JPanel panelEscaleno;
    private javax.swing.JPanel panelIsosceles;
    private javax.swing.JPanel panelRectangulo;
    private javax.swing.JTextField txtAlturaEq;
    private javax.swing.JTextField txtAlturaEs;
    private javax.swing.JTextField txtAlturaIs;
    private javax.swing.JTextField txtAlturaRe;
    private javax.swing.JTextField txtAreaEq;
    private javax.swing.JTextField txtAreaEs;
    private javax.swing.JTextField txtAreaIs;
    private javax.swing.JTextField txtAreaRe;
    private javax.swing.JTextField txtLado1Es;
    private javax.swing.JTextField txtLado1Is;
    private javax.swing.JTextField txtLado1Re;
    private javax.swing.JTextField txtLado2Es;
    private javax.swing.JTextField txtLado2Is;
    private javax.swing.JTextField txtLado2Re;
    private javax.swing.JTextField txtLado3Es;
    private javax.swing.JTextField txtPerimetroEq;
    private javax.swing.JTextField txtPerimetroEs;
    private javax.swing.JTextField txtPerimetroIs;
    private javax.swing.JTextField txtPerimetroRe;
    private javax.swing.JTextField txtladoEq;
    // End of variables declaration//GEN-END:variables
}
